### ISSUE TITLE
Unable to find an inherited method for function ‘getListElement’ for signature ‘"GRanges"’

### ISSUE THREAD

**Issue by AlexWanghaoming** [emilygoren/BinQuasi#1]
Dear emilygoren，
     When I ran BQ( ) with test data you offered, the error just came up as the title of Issues. I ran it with R-3.5.0, bioconductor 3.7 on CentOS6x. Could you please tell me what's the problem? Thanks

**Comment by AlexWanghaoming** [comment]
OK！Thank you very much！
> library(BinQuasi); devtools::session_info()
Warning: Your system is mis-configured: ‘/etc/localtime’ is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to ‘Asia/Chongqing’ (or equivalent)
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Chongqing              
 date     2018-06-19                  

Packages ----------------------------------------------------------------------
 package              * version   date      
 AnnotationDbi          1.42.1    2018-06-16
 assertthat             0.2.0     2017-04-11
 base                 * 3.5.0     2018-06-15
 BinQuasi             * 0.1-3     2018-06-16
 Biobase                2.40.0    2018-06-16
 BiocGenerics           0.26.0    2018-06-16
 BiocParallel           1.14.1    2018-06-16
 biomaRt                2.36.1    2018-06-16
 Biostrings             2.48.0    2018-06-16
 bit                    1.1-14    2018-05-29
 bit64                  0.9-7     2017-05-08
 bitops                 1.0-6     2013-08-17
 blob                   1.1.1     2018-03-25
 compiler               3.5.0     2018-06-15
 crayon                 1.3.4     2017-09-16
 csaw                   1.14.1    2018-06-16
 datasets             * 3.5.0     2018-06-15
 DBI                    1.0.0     2018-05-02
 DelayedArray           0.6.0     2018-06-16
 devtools               1.13.5    2018-02-18
 digest                 0.6.15    2018-01-28
 edgeR                  3.22.2    2018-06-16
 GenomeInfoDb           1.16.0    2018-06-16
 GenomeInfoDbData       1.1.0     2018-06-16
 GenomicAlignments      1.16.0    2018-06-16
 GenomicFeatures        1.32.0    2018-06-16
 GenomicRanges          1.32.3    2018-06-16
 graphics             * 3.5.0     2018-06-15
 grDevices            * 3.5.0     2018-06-15
 grid                   3.5.0     2018-06-15
 hms                    0.4.2     2018-03-10
 httr                   1.3.1     2017-08-20
 IRanges                2.14.10   2018-06-16
 lattice                0.20-35   2017-03-25
 limma                  3.36.1    2018-06-16
 locfit                 1.5-9.1   2013-04-20
 magrittr               1.5       2014-11-22
 Matrix                 1.2-14    2018-04-13
 matrixStats            0.53.1    2018-02-11
 memoise                1.1.0     2017-04-21
 methods              * 3.5.0     2018-06-15
 mgcv                   1.8-23    2018-01-21
 nlme                   3.1-137   2018-04-07
 parallel               3.5.0     2018-06-15
 pkgconfig              2.0.1     2017-03-21
 pracma                 2.1.4     2018-01-30
 prettyunits            1.0.2     2015-07-13
 progress               1.2.0     2018-06-14
 quadprog               1.5-5     2013-04-17
 R6                     2.2.2     2017-06-17
 Rcpp                   0.12.17   2018-05-18
 RCurl                  1.95-4.10 2018-01-04
 Rhtslib                1.12.1    2018-06-16
 rlang                  0.2.1     2018-05-30
 Rsamtools              1.32.0    2018-06-16
 RSQLite                2.1.1     2018-05-06
 rtracklayer            1.40.3    2018-06-16
 S4Vectors              0.18.3    2018-06-16
 stats                * 3.5.0     2018-06-15
 stats4                 3.5.0     2018-06-15
 stringi                1.2.3     2018-06-12
 stringr                1.3.1     2018-05-10
 SummarizedExperiment   1.10.1    2018-06-16
 tools                  3.5.0     2018-06-15
 utils                * 3.5.0     2018-06-15
 withr                  2.1.2     2018-03-15
 XML                    3.98-1.11 2018-06-11
 XVector                0.20.0    2018-06-16
 zlibbioc               1.26.0    2018-06-16
 source                              
 Bioconductor                        
 CRAN (R 3.5.0)                      
 local                               
 Github (emilygoren/BinQuasi@9f352f1)
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 local                               
 CRAN (R 3.5.0)                      
 Bioconductor                        
 local                               
 CRAN (R 3.5.0)                      
 Bioconductor                        
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 Bioconductor                        
 local                               
 local                               
 local                               
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 Bioconductor                        
 CRAN (R 3.5.0)                      
 Bioconductor                        
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 local                               
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 local                               
 CRAN (R 3.5.0)                      
 cran (@2.1.4)                       
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 cran (@1.5-5)                       
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 Bioconductor                        
 CRAN (R 3.5.0)                      
 Bioconductor                        
 CRAN (R 3.5.0)                      
 Bioconductor                        
 Bioconductor                        
 local                               
 local                               
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 Bioconductor                        
 local                               
 local                               
 CRAN (R 3.5.0)                      
 CRAN (R 3.5.0)                      
 Bioconductor                        
 Bioconductor                        
> 
Regards,
Alex

**Comment by emilygoren** [comment]
Thanks for the quick response. Looks like you are using an older version of the DelayedArray package (current is 0.6.1). I don't think this is causing the problem, but I'd still recommend updating all BioConductor packages with the code `source("https://bioconductor.org/biocLite.R"); biocLite()`

I have changed the application of `lapply` in the package code. Please try reinstalling the updated BinQuasi package via `devtools::install_github("emilygoren/BinQuasi", args = "--preclean", build_vignettes = TRUE)` and let me know if you still encounter the error.

**Comment by AlexWanghaoming** [comment]
Thanks Emily，I have run it successfully. I will ask you if I have some questions.

Thanks,
Alex
